### ISSUE TITLE
Create ERD

### ISSUE THREAD

**Issue by 1crowie1** [1crowie1/SIS-realestate#13]

**Comment by 1crowie1** [comment]
Completed with @treevesy 
- ![MicrosoftTeams-image](https://user-images.githubusercontent.com/39574251/188030031-e529d6a4-83bc-4f68-81a2-93cd75012e6e.png)

**Comment by treevesy** [comment]
v2.0 of the ERD we could consider removing the PropertyHistory and linking it to Sale since it is not a many to many relationship between Property and Sale

![Revised ERD v2 0](https://user-images.githubusercontent.com/63341855/188056506-43282a8f-5b28-4a67-8744-f4ab671bec2b.jpg)

**Comment by 1crowie1** [comment]
Suburb may require some abstracted attributes from house such as number of schools, if there is a train station, if it is a coastal suburb, etc.

**Comment by 1crowie1** [comment]
Created and Implemented
