### ISSUE TITLE
Setup Continuous Deployment Pipeline

### ISSUE THREAD

**Issue by 1crowie1** [1crowie1/SIS-realestate#16]

**Comment by anesu4** [comment]
Hosted Frontend via anesu4/Home-Finder Repo on Netlify:
https://homes-finder.netlify.app/

Implemented a CI Pipeline using CircleCI onto anesu4/Home-Finder Repo
https://app.circleci.com/pipelines/github/anesu4/Home-Finder

**Comment by 1crowie1** [comment]
Completed
